[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rna-bits"
version = "0.0.1"
authors = [
  { name="Paul-Andre Henegar", email="paul-andre.henegar@mail.mcgill.ca" },
]
dependencies = [
  "biopython",
  "numpy",
  "mmtf-python"
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
rna_builder = "rna_bits.builder.builder:main_wrapper"
bp2_bridge = "rna_bits.builder.bp2_bridge:main_wrapper"

